add_newline = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold yellow)"

[git_branch]
symbol = " "

[python]
symbol = "🐍 "
format = "[$symbol$version]($style) "

[nodejs]
disabled = true

[aws]
disabled = false

[kubernetes]
disabled = false

[time]
disabled = false
format = "[$time]($style) "
