[tools]
java = ["oracle-25", "oracle-21", "oracle-17"]
kubectl = "latest"
node = "latest"
python = ["3.14", "3.12"]
rust = "latest"
helm = "latest"
k9s = "latest"
kubectx = "latest"
stern = "latest"
argo = "latest"
argocd = "latest"
